/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "rustplus.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rustplus_Vector2, rustplus_Vector2, AUTO)


PB_BIND(rustplus_Vector3, rustplus_Vector3, AUTO)


PB_BIND(rustplus_Vector4, rustplus_Vector4, AUTO)


PB_BIND(rustplus_Half3, rustplus_Half3, AUTO)


PB_BIND(rustplus_Color, rustplus_Color, AUTO)


PB_BIND(rustplus_Ray, rustplus_Ray, AUTO)


PB_BIND(rustplus_ClanActionResult, rustplus_ClanActionResult, AUTO)


PB_BIND(rustplus_ClanInfo, rustplus_ClanInfo, AUTO)


PB_BIND(rustplus_ClanInfo_Role, rustplus_ClanInfo_Role, AUTO)


PB_BIND(rustplus_ClanInfo_Member, rustplus_ClanInfo_Member, AUTO)


PB_BIND(rustplus_ClanInfo_Invite, rustplus_ClanInfo_Invite, AUTO)


PB_BIND(rustplus_ClanLog, rustplus_ClanLog, AUTO)


PB_BIND(rustplus_ClanLog_Entry, rustplus_ClanLog_Entry, AUTO)


PB_BIND(rustplus_ClanInvitations, rustplus_ClanInvitations, AUTO)


PB_BIND(rustplus_ClanInvitations_Invitation, rustplus_ClanInvitations_Invitation, AUTO)


PB_BIND(rustplus_AppRequest, rustplus_AppRequest, 2)


PB_BIND(rustplus_AppMessage, rustplus_AppMessage, 2)


PB_BIND(rustplus_AppResponse, rustplus_AppResponse, 2)


PB_BIND(rustplus_AppBroadcast, rustplus_AppBroadcast, 2)


PB_BIND(rustplus_AppEmpty, rustplus_AppEmpty, AUTO)


PB_BIND(rustplus_AppSendMessage, rustplus_AppSendMessage, AUTO)


PB_BIND(rustplus_AppSetEntityValue, rustplus_AppSetEntityValue, AUTO)


PB_BIND(rustplus_AppPromoteToLeader, rustplus_AppPromoteToLeader, AUTO)


PB_BIND(rustplus_AppGetNexusAuth, rustplus_AppGetNexusAuth, AUTO)


PB_BIND(rustplus_AppSuccess, rustplus_AppSuccess, AUTO)


PB_BIND(rustplus_AppError, rustplus_AppError, AUTO)


PB_BIND(rustplus_AppFlag, rustplus_AppFlag, AUTO)


PB_BIND(rustplus_AppInfo, rustplus_AppInfo, AUTO)


PB_BIND(rustplus_AppTime, rustplus_AppTime, AUTO)


PB_BIND(rustplus_AppMap, rustplus_AppMap, AUTO)


PB_BIND(rustplus_AppMap_Monument, rustplus_AppMap_Monument, AUTO)


PB_BIND(rustplus_AppEntityInfo, rustplus_AppEntityInfo, AUTO)


PB_BIND(rustplus_AppEntityPayload, rustplus_AppEntityPayload, AUTO)


PB_BIND(rustplus_AppEntityPayload_Item, rustplus_AppEntityPayload_Item, AUTO)


PB_BIND(rustplus_AppTeamInfo, rustplus_AppTeamInfo, AUTO)


PB_BIND(rustplus_AppTeamInfo_Member, rustplus_AppTeamInfo_Member, AUTO)


PB_BIND(rustplus_AppTeamInfo_Note, rustplus_AppTeamInfo_Note, AUTO)


PB_BIND(rustplus_AppTeamMessage, rustplus_AppTeamMessage, AUTO)


PB_BIND(rustplus_AppTeamChat, rustplus_AppTeamChat, AUTO)


PB_BIND(rustplus_AppMarker, rustplus_AppMarker, AUTO)


PB_BIND(rustplus_AppMarker_SellOrder, rustplus_AppMarker_SellOrder, AUTO)


PB_BIND(rustplus_AppMapMarkers, rustplus_AppMapMarkers, AUTO)


PB_BIND(rustplus_AppClanInfo, rustplus_AppClanInfo, AUTO)


PB_BIND(rustplus_AppClanMessage, rustplus_AppClanMessage, AUTO)


PB_BIND(rustplus_AppClanChat, rustplus_AppClanChat, AUTO)


PB_BIND(rustplus_AppNexusAuth, rustplus_AppNexusAuth, AUTO)


PB_BIND(rustplus_AppTeamChanged, rustplus_AppTeamChanged, AUTO)


PB_BIND(rustplus_AppNewTeamMessage, rustplus_AppNewTeamMessage, AUTO)


PB_BIND(rustplus_AppEntityChanged, rustplus_AppEntityChanged, AUTO)


PB_BIND(rustplus_AppClanChanged, rustplus_AppClanChanged, AUTO)


PB_BIND(rustplus_AppNewClanMessage, rustplus_AppNewClanMessage, AUTO)


PB_BIND(rustplus_AppCameraSubscribe, rustplus_AppCameraSubscribe, AUTO)


PB_BIND(rustplus_AppCameraInput, rustplus_AppCameraInput, AUTO)


PB_BIND(rustplus_AppCameraInfo, rustplus_AppCameraInfo, AUTO)


PB_BIND(rustplus_AppCameraRays, rustplus_AppCameraRays, AUTO)


PB_BIND(rustplus_AppCameraRays_Entity, rustplus_AppCameraRays_Entity, AUTO)















