/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RUSTPLUS_RUSTPLUS_PB_H_INCLUDED
#define PB_RUSTPLUS_RUSTPLUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _rustplus_AppEntityType {
    rustplus_AppEntityType_Reserved = 0,
    rustplus_AppEntityType_Switch = 1,
    rustplus_AppEntityType_Alarm = 2,
    rustplus_AppEntityType_StorageMonitor = 3
} rustplus_AppEntityType;

typedef enum _rustplus_AppMarkerType {
    rustplus_AppMarkerType_Undefined = 0,
    rustplus_AppMarkerType_Player = 1,
    rustplus_AppMarkerType_Explosion = 2,
    rustplus_AppMarkerType_VendingMachine = 3,
    rustplus_AppMarkerType_CH47 = 4,
    rustplus_AppMarkerType_CargoShip = 5,
    rustplus_AppMarkerType_Crate = 6,
    rustplus_AppMarkerType_GenericRadius = 7,
    rustplus_AppMarkerType_PatrolHelicopter = 8,
    rustplus_AppMarkerType_TravellingVendor = 9
} rustplus_AppMarkerType;

typedef enum _rustplus_AppTeamInfo_Note_Type {
    rustplus_AppTeamInfo_Note_Type_Death = 0,
    rustplus_AppTeamInfo_Note_Type_PointOfInterest = 1
} rustplus_AppTeamInfo_Note_Type;

typedef enum _rustplus_AppTeamInfo_Note_Icon {
    rustplus_AppTeamInfo_Note_Icon_Pin = 0,
    rustplus_AppTeamInfo_Note_Icon_Dollar = 1,
    rustplus_AppTeamInfo_Note_Icon_Home = 2,
    rustplus_AppTeamInfo_Note_Icon_Parachute = 3,
    rustplus_AppTeamInfo_Note_Icon_Scope = 4,
    rustplus_AppTeamInfo_Note_Icon_Shield = 5,
    rustplus_AppTeamInfo_Note_Icon_Skull = 6,
    rustplus_AppTeamInfo_Note_Icon_Sleep = 7,
    rustplus_AppTeamInfo_Note_Icon_Zzz = 8,
    rustplus_AppTeamInfo_Note_Icon_Gun = 9,
    rustplus_AppTeamInfo_Note_Icon_Rock = 10,
    rustplus_AppTeamInfo_Note_Icon_Loot = 11
} rustplus_AppTeamInfo_Note_Icon;

typedef enum _rustplus_AppTeamInfo_Note_ColourIndex {
    rustplus_AppTeamInfo_Note_ColourIndex_Yellow = 0,
    rustplus_AppTeamInfo_Note_ColourIndex_Blue = 1,
    rustplus_AppTeamInfo_Note_ColourIndex_Green = 2,
    rustplus_AppTeamInfo_Note_ColourIndex_Red = 3,
    rustplus_AppTeamInfo_Note_ColourIndex_Purple = 4,
    rustplus_AppTeamInfo_Note_ColourIndex_Cyan = 5
} rustplus_AppTeamInfo_Note_ColourIndex;

typedef enum _rustplus_AppCameraRays_EntityType {
    rustplus_AppCameraRays_EntityType_Reserved = 0,
    rustplus_AppCameraRays_EntityType_Tree = 1,
    rustplus_AppCameraRays_EntityType_Player = 2
} rustplus_AppCameraRays_EntityType;

/* Struct definitions */
typedef struct _rustplus_Vector2 {
    float x;
    float y;
} rustplus_Vector2;

typedef struct _rustplus_Vector3 {
    float x;
    float y;
    float z;
} rustplus_Vector3;

typedef struct _rustplus_Vector4 {
    float x;
    float y;
    float z;
    float w;
} rustplus_Vector4;

typedef struct _rustplus_Half3 {
    float x;
    float y;
    float z;
} rustplus_Half3;

typedef struct _rustplus_Color {
    float r;
    float g;
    float b;
    float a;
} rustplus_Color;

typedef struct _rustplus_Ray {
    bool has_origin;
    rustplus_Vector3 origin;
    bool has_direction;
    rustplus_Vector3 direction;
} rustplus_Ray;

typedef struct _rustplus_ClanInfo {
    int64_t clanId;
    pb_callback_t name;
    int64_t created;
    uint64_t creator;
    pb_callback_t motd;
    int64_t motdTimestamp;
    uint64_t motdAuthor;
    pb_callback_t logo;
    int32_t color;
    pb_callback_t roles;
    pb_callback_t members;
    pb_callback_t invites;
    bool has_maxMemberCount;
    int32_t maxMemberCount;
    int64_t score;
} rustplus_ClanInfo;

typedef struct _rustplus_ClanActionResult {
    int32_t requestId;
    int32_t result;
    bool hasClanInfo;
    bool has_clanInfo;
    rustplus_ClanInfo clanInfo;
} rustplus_ClanActionResult;

typedef struct _rustplus_ClanInfo_Role {
    int32_t roleId;
    int32_t rank;
    pb_callback_t name;
    bool canSetMotd;
    bool canSetLogo;
    bool canInvite;
    bool canKick;
    bool canPromote;
    bool canDemote;
    bool canSetPlayerNotes;
    bool canAccessLogs;
    bool canAccessScoreEvents;
} rustplus_ClanInfo_Role;

typedef struct _rustplus_ClanInfo_Member {
    uint64_t steamId;
    int32_t roleId;
    int64_t joined;
    int64_t lastSeen;
    pb_callback_t notes;
    bool online;
} rustplus_ClanInfo_Member;

typedef struct _rustplus_ClanInfo_Invite {
    uint64_t steamId;
    uint64_t recruiter;
    int64_t timestamp;
} rustplus_ClanInfo_Invite;

typedef struct _rustplus_ClanLog {
    int64_t clanId;
    pb_callback_t logEntries;
} rustplus_ClanLog;

typedef struct _rustplus_ClanLog_Entry {
    int64_t timestamp;
    pb_callback_t eventKey;
    pb_callback_t arg1;
    pb_callback_t arg2;
    pb_callback_t arg3;
    pb_callback_t arg4;
} rustplus_ClanLog_Entry;

typedef struct _rustplus_ClanInvitations {
    pb_callback_t invitations;
} rustplus_ClanInvitations;

typedef struct _rustplus_ClanInvitations_Invitation {
    int64_t clanId;
    uint64_t recruiter;
    int64_t timestamp;
} rustplus_ClanInvitations_Invitation;

typedef struct _rustplus_AppEmpty {
    char dummy_field;
} rustplus_AppEmpty;

typedef struct _rustplus_AppSendMessage {
    pb_callback_t message;
} rustplus_AppSendMessage;

typedef struct _rustplus_AppSetEntityValue {
    bool value;
} rustplus_AppSetEntityValue;

typedef struct _rustplus_AppPromoteToLeader {
    uint64_t steamId;
} rustplus_AppPromoteToLeader;

typedef struct _rustplus_AppGetNexusAuth {
    pb_callback_t appKey;
} rustplus_AppGetNexusAuth;

typedef struct _rustplus_AppSuccess {
    char dummy_field;
} rustplus_AppSuccess;

typedef struct _rustplus_AppError {
    pb_callback_t error;
} rustplus_AppError;

typedef struct _rustplus_AppFlag {
    bool has_value;
    bool value;
} rustplus_AppFlag;

typedef struct _rustplus_AppInfo {
    pb_callback_t name;
    pb_callback_t headerImage;
    pb_callback_t url;
    pb_callback_t map;
    uint32_t mapSize;
    uint32_t wipeTime;
    uint32_t players;
    uint32_t maxPlayers;
    uint32_t queuedPlayers;
    uint32_t seed;
    uint32_t salt;
    pb_callback_t logoImage;
    pb_callback_t nexus;
    int32_t nexusId;
    pb_callback_t nexusZone;
    bool camerasEnabled;
} rustplus_AppInfo;

typedef struct _rustplus_AppTime {
    float dayLengthMinutes;
    float timeScale;
    float sunrise;
    float sunset;
    float time;
} rustplus_AppTime;

typedef struct _rustplus_AppMap {
    uint32_t width;
    uint32_t height;
    pb_callback_t jpgImage;
    int32_t oceanMargin;
    pb_callback_t monuments;
    pb_callback_t background;
} rustplus_AppMap;

typedef struct _rustplus_AppMap_Monument {
    pb_callback_t token;
    float x;
    float y;
} rustplus_AppMap_Monument;

typedef struct _rustplus_AppEntityPayload {
    bool value;
    pb_callback_t items;
    int32_t capacity;
    bool has_hasProtection;
    bool hasProtection;
    uint32_t protectionExpiry;
} rustplus_AppEntityPayload;

typedef struct _rustplus_AppEntityInfo {
    rustplus_AppEntityType type;
    bool has_payload;
    rustplus_AppEntityPayload payload;
} rustplus_AppEntityInfo;

typedef struct _rustplus_AppEntityPayload_Item {
    int32_t itemId;
    int32_t quantity;
    bool itemIsBlueprint;
} rustplus_AppEntityPayload_Item;

typedef struct _rustplus_AppTeamInfo {
    uint64_t leaderSteamId;
    pb_callback_t members;
    pb_callback_t mapNotes;
    pb_callback_t leaderMapNotes;
} rustplus_AppTeamInfo;

typedef struct _rustplus_AppTeamInfo_Member {
    uint64_t steamId;
    pb_callback_t name;
    float x;
    float y;
    bool isOnline;
    uint32_t spawnTime;
    bool isAlive;
    uint32_t deathTime;
} rustplus_AppTeamInfo_Member;

typedef struct _rustplus_AppTeamInfo_Note {
    rustplus_AppTeamInfo_Note_Type type;
    float x;
    float y;
    rustplus_AppTeamInfo_Note_Icon icon;
    rustplus_AppTeamInfo_Note_ColourIndex colourIndex;
    pb_callback_t label;
} rustplus_AppTeamInfo_Note;

typedef struct _rustplus_AppTeamMessage {
    uint64_t steamId;
    pb_callback_t name;
    pb_callback_t message;
    pb_callback_t color;
    uint32_t time;
} rustplus_AppTeamMessage;

typedef struct _rustplus_AppTeamChat {
    pb_callback_t messages;
} rustplus_AppTeamChat;

typedef struct _rustplus_AppMarker {
    uint32_t id;
    rustplus_AppMarkerType type;
    float x;
    float y;
    uint64_t steamId;
    float rotation;
    float radius;
    bool has_color1;
    rustplus_Vector4 color1;
    bool has_color2;
    rustplus_Vector4 color2;
    float alpha;
    pb_callback_t name;
    bool outOfStock;
    pb_callback_t sellOrders;
} rustplus_AppMarker;

typedef struct _rustplus_AppMarker_SellOrder {
    int32_t itemId;
    int32_t quantity;
    int32_t currencyId;
    int32_t costPerItem;
    int32_t amountInStock;
    bool itemIsBlueprint;
    bool currencyIsBlueprint;
    float itemCondition;
    float itemConditionMax;
    float priceMultiplier;
} rustplus_AppMarker_SellOrder;

typedef struct _rustplus_AppMapMarkers {
    pb_callback_t markers;
} rustplus_AppMapMarkers;

typedef struct _rustplus_AppClanInfo {
    bool has_clanInfo;
    rustplus_ClanInfo clanInfo;
} rustplus_AppClanInfo;

typedef struct _rustplus_AppClanMessage {
    uint64_t steamId;
    pb_callback_t name;
    pb_callback_t message;
    int64_t time;
} rustplus_AppClanMessage;

typedef struct _rustplus_AppClanChat {
    pb_callback_t messages;
} rustplus_AppClanChat;

typedef struct _rustplus_AppNexusAuth {
    pb_callback_t serverId;
    int32_t playerToken;
} rustplus_AppNexusAuth;

typedef struct _rustplus_AppTeamChanged {
    uint64_t playerId;
    bool has_teamInfo;
    rustplus_AppTeamInfo teamInfo;
} rustplus_AppTeamChanged;

typedef struct _rustplus_AppNewTeamMessage {
    bool has_message;
    rustplus_AppTeamMessage message;
} rustplus_AppNewTeamMessage;

typedef struct _rustplus_AppEntityChanged {
    bool has_entityId;
    uint32_t entityId;
    bool has_payload;
    rustplus_AppEntityPayload payload;
} rustplus_AppEntityChanged;

typedef struct _rustplus_AppClanChanged {
    bool has_clanInfo;
    rustplus_ClanInfo clanInfo;
} rustplus_AppClanChanged;

typedef struct _rustplus_AppNewClanMessage {
    int64_t clanId;
    bool has_message;
    rustplus_AppClanMessage message;
} rustplus_AppNewClanMessage;

typedef struct _rustplus_AppCameraSubscribe {
    pb_callback_t cameraId;
} rustplus_AppCameraSubscribe;

typedef struct _rustplus_AppCameraInput {
    int32_t buttons;
    bool has_mouseDelta;
    rustplus_Vector2 mouseDelta;
} rustplus_AppCameraInput;

typedef struct _rustplus_AppRequest {
    uint32_t seq;
    uint64_t playerId;
    int32_t playerToken;
    bool has_entityId;
    uint32_t entityId;
    bool has_getInfo;
    rustplus_AppEmpty getInfo;
    bool has_getTime;
    rustplus_AppEmpty getTime;
    bool has_getMap;
    rustplus_AppEmpty getMap;
    bool has_getTeamInfo;
    rustplus_AppEmpty getTeamInfo;
    bool has_getTeamChat;
    rustplus_AppEmpty getTeamChat;
    bool has_sendTeamMessage;
    rustplus_AppSendMessage sendTeamMessage;
    bool has_getEntityInfo;
    rustplus_AppEmpty getEntityInfo;
    bool has_setEntityValue;
    rustplus_AppSetEntityValue setEntityValue;
    bool has_checkSubscription;
    rustplus_AppEmpty checkSubscription;
    bool has_setSubscription;
    rustplus_AppFlag setSubscription;
    bool has_getMapMarkers;
    rustplus_AppEmpty getMapMarkers;
    bool has_promoteToLeader;
    rustplus_AppPromoteToLeader promoteToLeader;
    bool has_getClanInfo;
    rustplus_AppEmpty getClanInfo;
    bool has_setClanMotd;
    rustplus_AppSendMessage setClanMotd;
    bool has_getClanChat;
    rustplus_AppEmpty getClanChat;
    bool has_sendClanMessage;
    rustplus_AppSendMessage sendClanMessage;
    bool has_getNexusAuth;
    rustplus_AppGetNexusAuth getNexusAuth;
    bool has_cameraSubscribe;
    rustplus_AppCameraSubscribe cameraSubscribe;
    bool has_cameraUnsubscribe;
    rustplus_AppEmpty cameraUnsubscribe;
    bool has_cameraInput;
    rustplus_AppCameraInput cameraInput;
} rustplus_AppRequest;

typedef struct _rustplus_AppCameraInfo {
    int32_t width;
    int32_t height;
    float nearPlane;
    float farPlane;
    int32_t controlFlags;
} rustplus_AppCameraInfo;

typedef struct _rustplus_AppResponse {
    uint32_t seq;
    bool has_success;
    rustplus_AppSuccess success;
    bool has_error;
    rustplus_AppError error;
    bool has_info;
    rustplus_AppInfo info;
    bool has_time;
    rustplus_AppTime time;
    bool has_map;
    rustplus_AppMap map;
    bool has_teamInfo;
    rustplus_AppTeamInfo teamInfo;
    bool has_teamChat;
    rustplus_AppTeamChat teamChat;
    bool has_entityInfo;
    rustplus_AppEntityInfo entityInfo;
    bool has_flag;
    rustplus_AppFlag flag;
    bool has_mapMarkers;
    rustplus_AppMapMarkers mapMarkers;
    bool has_clanInfo;
    rustplus_AppClanInfo clanInfo;
    bool has_clanChat;
    rustplus_AppClanChat clanChat;
    bool has_nexusAuth;
    rustplus_AppNexusAuth nexusAuth;
    bool has_cameraSubscribeInfo;
    rustplus_AppCameraInfo cameraSubscribeInfo;
} rustplus_AppResponse;

typedef struct _rustplus_AppCameraRays {
    float verticalFov;
    int32_t sampleOffset;
    pb_callback_t rayData;
    float distance;
    pb_callback_t entities;
    float timeOfDay;
} rustplus_AppCameraRays;

typedef struct _rustplus_AppBroadcast {
    bool has_teamChanged;
    rustplus_AppTeamChanged teamChanged;
    bool has_teamMessage;
    rustplus_AppNewTeamMessage teamMessage;
    bool has_entityChanged;
    rustplus_AppEntityChanged entityChanged;
    bool has_clanChanged;
    rustplus_AppClanChanged clanChanged;
    bool has_clanMessage;
    rustplus_AppNewClanMessage clanMessage;
    bool has_cameraRays;
    rustplus_AppCameraRays cameraRays;
} rustplus_AppBroadcast;

typedef struct _rustplus_AppMessage {
    bool has_response;
    rustplus_AppResponse response;
    bool has_broadcast;
    rustplus_AppBroadcast broadcast;
} rustplus_AppMessage;

typedef struct _rustplus_AppCameraRays_Entity {
    uint32_t entityId;
    rustplus_AppCameraRays_EntityType type;
    bool has_position;
    rustplus_Vector3 position;
    bool has_rotation;
    rustplus_Vector3 rotation;
    bool has_size;
    rustplus_Vector3 size;
    pb_callback_t name;
} rustplus_AppCameraRays_Entity;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _rustplus_AppEntityType_MIN rustplus_AppEntityType_Reserved
#define _rustplus_AppEntityType_MAX rustplus_AppEntityType_StorageMonitor
#define _rustplus_AppEntityType_ARRAYSIZE ((rustplus_AppEntityType)(rustplus_AppEntityType_StorageMonitor+1))

#define _rustplus_AppMarkerType_MIN rustplus_AppMarkerType_Undefined
#define _rustplus_AppMarkerType_MAX rustplus_AppMarkerType_TravellingVendor
#define _rustplus_AppMarkerType_ARRAYSIZE ((rustplus_AppMarkerType)(rustplus_AppMarkerType_TravellingVendor+1))

#define _rustplus_AppTeamInfo_Note_Type_MIN rustplus_AppTeamInfo_Note_Type_Death
#define _rustplus_AppTeamInfo_Note_Type_MAX rustplus_AppTeamInfo_Note_Type_PointOfInterest
#define _rustplus_AppTeamInfo_Note_Type_ARRAYSIZE ((rustplus_AppTeamInfo_Note_Type)(rustplus_AppTeamInfo_Note_Type_PointOfInterest+1))

#define _rustplus_AppTeamInfo_Note_Icon_MIN rustplus_AppTeamInfo_Note_Icon_Pin
#define _rustplus_AppTeamInfo_Note_Icon_MAX rustplus_AppTeamInfo_Note_Icon_Loot
#define _rustplus_AppTeamInfo_Note_Icon_ARRAYSIZE ((rustplus_AppTeamInfo_Note_Icon)(rustplus_AppTeamInfo_Note_Icon_Loot+1))

#define _rustplus_AppTeamInfo_Note_ColourIndex_MIN rustplus_AppTeamInfo_Note_ColourIndex_Yellow
#define _rustplus_AppTeamInfo_Note_ColourIndex_MAX rustplus_AppTeamInfo_Note_ColourIndex_Cyan
#define _rustplus_AppTeamInfo_Note_ColourIndex_ARRAYSIZE ((rustplus_AppTeamInfo_Note_ColourIndex)(rustplus_AppTeamInfo_Note_ColourIndex_Cyan+1))

#define _rustplus_AppCameraRays_EntityType_MIN rustplus_AppCameraRays_EntityType_Reserved
#define _rustplus_AppCameraRays_EntityType_MAX rustplus_AppCameraRays_EntityType_Player
#define _rustplus_AppCameraRays_EntityType_ARRAYSIZE ((rustplus_AppCameraRays_EntityType)(rustplus_AppCameraRays_EntityType_Player+1))
































#define rustplus_AppEntityInfo_type_ENUMTYPE rustplus_AppEntityType





#define rustplus_AppTeamInfo_Note_type_ENUMTYPE rustplus_AppTeamInfo_Note_Type
#define rustplus_AppTeamInfo_Note_icon_ENUMTYPE rustplus_AppTeamInfo_Note_Icon
#define rustplus_AppTeamInfo_Note_colourIndex_ENUMTYPE rustplus_AppTeamInfo_Note_ColourIndex



#define rustplus_AppMarker_type_ENUMTYPE rustplus_AppMarkerType
















#define rustplus_AppCameraRays_Entity_type_ENUMTYPE rustplus_AppCameraRays_EntityType


/* Initializer values for message structs */
#define rustplus_Vector2_init_default            {0, 0}
#define rustplus_Vector3_init_default            {0, 0, 0}
#define rustplus_Vector4_init_default            {0, 0, 0, 0}
#define rustplus_Half3_init_default              {0, 0, 0}
#define rustplus_Color_init_default              {0, 0, 0, 0}
#define rustplus_Ray_init_default                {false, rustplus_Vector3_init_default, false, rustplus_Vector3_init_default}
#define rustplus_ClanActionResult_init_default   {0, 0, 0, false, rustplus_ClanInfo_init_default}
#define rustplus_ClanInfo_init_default           {0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0}
#define rustplus_ClanInfo_Role_init_default      {0, 0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rustplus_ClanInfo_Member_init_default    {0, 0, 0, 0, {{NULL}, NULL}, 0}
#define rustplus_ClanInfo_Invite_init_default    {0, 0, 0}
#define rustplus_ClanLog_init_default            {0, {{NULL}, NULL}}
#define rustplus_ClanLog_Entry_init_default      {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_ClanInvitations_init_default    {{{NULL}, NULL}}
#define rustplus_ClanInvitations_Invitation_init_default {0, 0, 0}
#define rustplus_AppRequest_init_default         {0, 0, 0, false, 0, false, rustplus_AppEmpty_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppSendMessage_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppSetEntityValue_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppFlag_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppPromoteToLeader_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppSendMessage_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppSendMessage_init_default, false, rustplus_AppGetNexusAuth_init_default, false, rustplus_AppCameraSubscribe_init_default, false, rustplus_AppEmpty_init_default, false, rustplus_AppCameraInput_init_default}
#define rustplus_AppMessage_init_default         {false, rustplus_AppResponse_init_default, false, rustplus_AppBroadcast_init_default}
#define rustplus_AppResponse_init_default        {0, false, rustplus_AppSuccess_init_default, false, rustplus_AppError_init_default, false, rustplus_AppInfo_init_default, false, rustplus_AppTime_init_default, false, rustplus_AppMap_init_default, false, rustplus_AppTeamInfo_init_default, false, rustplus_AppTeamChat_init_default, false, rustplus_AppEntityInfo_init_default, false, rustplus_AppFlag_init_default, false, rustplus_AppMapMarkers_init_default, false, rustplus_AppClanInfo_init_default, false, rustplus_AppClanChat_init_default, false, rustplus_AppNexusAuth_init_default, false, rustplus_AppCameraInfo_init_default}
#define rustplus_AppBroadcast_init_default       {false, rustplus_AppTeamChanged_init_default, false, rustplus_AppNewTeamMessage_init_default, false, rustplus_AppEntityChanged_init_default, false, rustplus_AppClanChanged_init_default, false, rustplus_AppNewClanMessage_init_default, false, rustplus_AppCameraRays_init_default}
#define rustplus_AppEmpty_init_default           {0}
#define rustplus_AppSendMessage_init_default     {{{NULL}, NULL}}
#define rustplus_AppSetEntityValue_init_default  {0}
#define rustplus_AppPromoteToLeader_init_default {0}
#define rustplus_AppGetNexusAuth_init_default    {{{NULL}, NULL}}
#define rustplus_AppSuccess_init_default         {0}
#define rustplus_AppError_init_default           {{{NULL}, NULL}}
#define rustplus_AppFlag_init_default            {false, 0}
#define rustplus_AppInfo_init_default            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define rustplus_AppTime_init_default            {0, 0, 0, 0, 0}
#define rustplus_AppMap_init_default             {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_AppMap_Monument_init_default    {{{NULL}, NULL}, 0, 0}
#define rustplus_AppEntityInfo_init_default      {_rustplus_AppEntityType_MIN, false, rustplus_AppEntityPayload_init_default}
#define rustplus_AppEntityPayload_init_default   {0, {{NULL}, NULL}, 0, false, 0, 0}
#define rustplus_AppEntityPayload_Item_init_default {0, 0, 0}
#define rustplus_AppTeamInfo_init_default        {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_AppTeamInfo_Member_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define rustplus_AppTeamInfo_Note_init_default   {_rustplus_AppTeamInfo_Note_Type_MIN, 0, 0, _rustplus_AppTeamInfo_Note_Icon_MIN, _rustplus_AppTeamInfo_Note_ColourIndex_MIN, {{NULL}, NULL}}
#define rustplus_AppTeamMessage_init_default     {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define rustplus_AppTeamChat_init_default        {{{NULL}, NULL}}
#define rustplus_AppMarker_init_default          {0, _rustplus_AppMarkerType_MIN, 0, 0, 0, 0, 0, false, rustplus_Vector4_init_default, false, rustplus_Vector4_init_default, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define rustplus_AppMarker_SellOrder_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rustplus_AppMapMarkers_init_default      {{{NULL}, NULL}}
#define rustplus_AppClanInfo_init_default        {false, rustplus_ClanInfo_init_default}
#define rustplus_AppClanMessage_init_default     {0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define rustplus_AppClanChat_init_default        {{{NULL}, NULL}}
#define rustplus_AppNexusAuth_init_default       {{{NULL}, NULL}, 0}
#define rustplus_AppTeamChanged_init_default     {0, false, rustplus_AppTeamInfo_init_default}
#define rustplus_AppNewTeamMessage_init_default  {false, rustplus_AppTeamMessage_init_default}
#define rustplus_AppEntityChanged_init_default   {false, 0, false, rustplus_AppEntityPayload_init_default}
#define rustplus_AppClanChanged_init_default     {false, rustplus_ClanInfo_init_default}
#define rustplus_AppNewClanMessage_init_default  {0, false, rustplus_AppClanMessage_init_default}
#define rustplus_AppCameraSubscribe_init_default {{{NULL}, NULL}}
#define rustplus_AppCameraInput_init_default     {0, false, rustplus_Vector2_init_default}
#define rustplus_AppCameraInfo_init_default      {0, 0, 0, 0, 0}
#define rustplus_AppCameraRays_init_default      {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define rustplus_AppCameraRays_Entity_init_default {0, _rustplus_AppCameraRays_EntityType_MIN, false, rustplus_Vector3_init_default, false, rustplus_Vector3_init_default, false, rustplus_Vector3_init_default, {{NULL}, NULL}}
#define rustplus_Vector2_init_zero               {0, 0}
#define rustplus_Vector3_init_zero               {0, 0, 0}
#define rustplus_Vector4_init_zero               {0, 0, 0, 0}
#define rustplus_Half3_init_zero                 {0, 0, 0}
#define rustplus_Color_init_zero                 {0, 0, 0, 0}
#define rustplus_Ray_init_zero                   {false, rustplus_Vector3_init_zero, false, rustplus_Vector3_init_zero}
#define rustplus_ClanActionResult_init_zero      {0, 0, 0, false, rustplus_ClanInfo_init_zero}
#define rustplus_ClanInfo_init_zero              {0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0}
#define rustplus_ClanInfo_Role_init_zero         {0, 0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rustplus_ClanInfo_Member_init_zero       {0, 0, 0, 0, {{NULL}, NULL}, 0}
#define rustplus_ClanInfo_Invite_init_zero       {0, 0, 0}
#define rustplus_ClanLog_init_zero               {0, {{NULL}, NULL}}
#define rustplus_ClanLog_Entry_init_zero         {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_ClanInvitations_init_zero       {{{NULL}, NULL}}
#define rustplus_ClanInvitations_Invitation_init_zero {0, 0, 0}
#define rustplus_AppRequest_init_zero            {0, 0, 0, false, 0, false, rustplus_AppEmpty_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppSendMessage_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppSetEntityValue_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppFlag_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppPromoteToLeader_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppSendMessage_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppSendMessage_init_zero, false, rustplus_AppGetNexusAuth_init_zero, false, rustplus_AppCameraSubscribe_init_zero, false, rustplus_AppEmpty_init_zero, false, rustplus_AppCameraInput_init_zero}
#define rustplus_AppMessage_init_zero            {false, rustplus_AppResponse_init_zero, false, rustplus_AppBroadcast_init_zero}
#define rustplus_AppResponse_init_zero           {0, false, rustplus_AppSuccess_init_zero, false, rustplus_AppError_init_zero, false, rustplus_AppInfo_init_zero, false, rustplus_AppTime_init_zero, false, rustplus_AppMap_init_zero, false, rustplus_AppTeamInfo_init_zero, false, rustplus_AppTeamChat_init_zero, false, rustplus_AppEntityInfo_init_zero, false, rustplus_AppFlag_init_zero, false, rustplus_AppMapMarkers_init_zero, false, rustplus_AppClanInfo_init_zero, false, rustplus_AppClanChat_init_zero, false, rustplus_AppNexusAuth_init_zero, false, rustplus_AppCameraInfo_init_zero}
#define rustplus_AppBroadcast_init_zero          {false, rustplus_AppTeamChanged_init_zero, false, rustplus_AppNewTeamMessage_init_zero, false, rustplus_AppEntityChanged_init_zero, false, rustplus_AppClanChanged_init_zero, false, rustplus_AppNewClanMessage_init_zero, false, rustplus_AppCameraRays_init_zero}
#define rustplus_AppEmpty_init_zero              {0}
#define rustplus_AppSendMessage_init_zero        {{{NULL}, NULL}}
#define rustplus_AppSetEntityValue_init_zero     {0}
#define rustplus_AppPromoteToLeader_init_zero    {0}
#define rustplus_AppGetNexusAuth_init_zero       {{{NULL}, NULL}}
#define rustplus_AppSuccess_init_zero            {0}
#define rustplus_AppError_init_zero              {{{NULL}, NULL}}
#define rustplus_AppFlag_init_zero               {false, 0}
#define rustplus_AppInfo_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define rustplus_AppTime_init_zero               {0, 0, 0, 0, 0}
#define rustplus_AppMap_init_zero                {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_AppMap_Monument_init_zero       {{{NULL}, NULL}, 0, 0}
#define rustplus_AppEntityInfo_init_zero         {_rustplus_AppEntityType_MIN, false, rustplus_AppEntityPayload_init_zero}
#define rustplus_AppEntityPayload_init_zero      {0, {{NULL}, NULL}, 0, false, 0, 0}
#define rustplus_AppEntityPayload_Item_init_zero {0, 0, 0}
#define rustplus_AppTeamInfo_init_zero           {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define rustplus_AppTeamInfo_Member_init_zero    {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define rustplus_AppTeamInfo_Note_init_zero      {_rustplus_AppTeamInfo_Note_Type_MIN, 0, 0, _rustplus_AppTeamInfo_Note_Icon_MIN, _rustplus_AppTeamInfo_Note_ColourIndex_MIN, {{NULL}, NULL}}
#define rustplus_AppTeamMessage_init_zero        {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define rustplus_AppTeamChat_init_zero           {{{NULL}, NULL}}
#define rustplus_AppMarker_init_zero             {0, _rustplus_AppMarkerType_MIN, 0, 0, 0, 0, 0, false, rustplus_Vector4_init_zero, false, rustplus_Vector4_init_zero, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define rustplus_AppMarker_SellOrder_init_zero   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rustplus_AppMapMarkers_init_zero         {{{NULL}, NULL}}
#define rustplus_AppClanInfo_init_zero           {false, rustplus_ClanInfo_init_zero}
#define rustplus_AppClanMessage_init_zero        {0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define rustplus_AppClanChat_init_zero           {{{NULL}, NULL}}
#define rustplus_AppNexusAuth_init_zero          {{{NULL}, NULL}, 0}
#define rustplus_AppTeamChanged_init_zero        {0, false, rustplus_AppTeamInfo_init_zero}
#define rustplus_AppNewTeamMessage_init_zero     {false, rustplus_AppTeamMessage_init_zero}
#define rustplus_AppEntityChanged_init_zero      {false, 0, false, rustplus_AppEntityPayload_init_zero}
#define rustplus_AppClanChanged_init_zero        {false, rustplus_ClanInfo_init_zero}
#define rustplus_AppNewClanMessage_init_zero     {0, false, rustplus_AppClanMessage_init_zero}
#define rustplus_AppCameraSubscribe_init_zero    {{{NULL}, NULL}}
#define rustplus_AppCameraInput_init_zero        {0, false, rustplus_Vector2_init_zero}
#define rustplus_AppCameraInfo_init_zero         {0, 0, 0, 0, 0}
#define rustplus_AppCameraRays_init_zero         {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define rustplus_AppCameraRays_Entity_init_zero  {0, _rustplus_AppCameraRays_EntityType_MIN, false, rustplus_Vector3_init_zero, false, rustplus_Vector3_init_zero, false, rustplus_Vector3_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define rustplus_Vector2_x_tag                   1
#define rustplus_Vector2_y_tag                   2
#define rustplus_Vector3_x_tag                   1
#define rustplus_Vector3_y_tag                   2
#define rustplus_Vector3_z_tag                   3
#define rustplus_Vector4_x_tag                   1
#define rustplus_Vector4_y_tag                   2
#define rustplus_Vector4_z_tag                   3
#define rustplus_Vector4_w_tag                   4
#define rustplus_Half3_x_tag                     1
#define rustplus_Half3_y_tag                     2
#define rustplus_Half3_z_tag                     3
#define rustplus_Color_r_tag                     1
#define rustplus_Color_g_tag                     2
#define rustplus_Color_b_tag                     3
#define rustplus_Color_a_tag                     4
#define rustplus_Ray_origin_tag                  1
#define rustplus_Ray_direction_tag               2
#define rustplus_ClanInfo_clanId_tag             1
#define rustplus_ClanInfo_name_tag               2
#define rustplus_ClanInfo_created_tag            3
#define rustplus_ClanInfo_creator_tag            4
#define rustplus_ClanInfo_motd_tag               5
#define rustplus_ClanInfo_motdTimestamp_tag      6
#define rustplus_ClanInfo_motdAuthor_tag         7
#define rustplus_ClanInfo_logo_tag               8
#define rustplus_ClanInfo_color_tag              9
#define rustplus_ClanInfo_roles_tag              10
#define rustplus_ClanInfo_members_tag            11
#define rustplus_ClanInfo_invites_tag            12
#define rustplus_ClanInfo_maxMemberCount_tag     13
#define rustplus_ClanInfo_score_tag              14
#define rustplus_ClanActionResult_requestId_tag  1
#define rustplus_ClanActionResult_result_tag     2
#define rustplus_ClanActionResult_hasClanInfo_tag 3
#define rustplus_ClanActionResult_clanInfo_tag   4
#define rustplus_ClanInfo_Role_roleId_tag        1
#define rustplus_ClanInfo_Role_rank_tag          2
#define rustplus_ClanInfo_Role_name_tag          3
#define rustplus_ClanInfo_Role_canSetMotd_tag    4
#define rustplus_ClanInfo_Role_canSetLogo_tag    5
#define rustplus_ClanInfo_Role_canInvite_tag     6
#define rustplus_ClanInfo_Role_canKick_tag       7
#define rustplus_ClanInfo_Role_canPromote_tag    8
#define rustplus_ClanInfo_Role_canDemote_tag     9
#define rustplus_ClanInfo_Role_canSetPlayerNotes_tag 10
#define rustplus_ClanInfo_Role_canAccessLogs_tag 11
#define rustplus_ClanInfo_Role_canAccessScoreEvents_tag 12
#define rustplus_ClanInfo_Member_steamId_tag     1
#define rustplus_ClanInfo_Member_roleId_tag      2
#define rustplus_ClanInfo_Member_joined_tag      3
#define rustplus_ClanInfo_Member_lastSeen_tag    4
#define rustplus_ClanInfo_Member_notes_tag       5
#define rustplus_ClanInfo_Member_online_tag      6
#define rustplus_ClanInfo_Invite_steamId_tag     1
#define rustplus_ClanInfo_Invite_recruiter_tag   2
#define rustplus_ClanInfo_Invite_timestamp_tag   3
#define rustplus_ClanLog_clanId_tag              1
#define rustplus_ClanLog_logEntries_tag          2
#define rustplus_ClanLog_Entry_timestamp_tag     1
#define rustplus_ClanLog_Entry_eventKey_tag      2
#define rustplus_ClanLog_Entry_arg1_tag          3
#define rustplus_ClanLog_Entry_arg2_tag          4
#define rustplus_ClanLog_Entry_arg3_tag          5
#define rustplus_ClanLog_Entry_arg4_tag          6
#define rustplus_ClanInvitations_invitations_tag 1
#define rustplus_ClanInvitations_Invitation_clanId_tag 1
#define rustplus_ClanInvitations_Invitation_recruiter_tag 2
#define rustplus_ClanInvitations_Invitation_timestamp_tag 3
#define rustplus_AppSendMessage_message_tag      1
#define rustplus_AppSetEntityValue_value_tag     1
#define rustplus_AppPromoteToLeader_steamId_tag  1
#define rustplus_AppGetNexusAuth_appKey_tag      1
#define rustplus_AppError_error_tag              1
#define rustplus_AppFlag_value_tag               1
#define rustplus_AppInfo_name_tag                1
#define rustplus_AppInfo_headerImage_tag         2
#define rustplus_AppInfo_url_tag                 3
#define rustplus_AppInfo_map_tag                 4
#define rustplus_AppInfo_mapSize_tag             5
#define rustplus_AppInfo_wipeTime_tag            6
#define rustplus_AppInfo_players_tag             7
#define rustplus_AppInfo_maxPlayers_tag          8
#define rustplus_AppInfo_queuedPlayers_tag       9
#define rustplus_AppInfo_seed_tag                10
#define rustplus_AppInfo_salt_tag                11
#define rustplus_AppInfo_logoImage_tag           12
#define rustplus_AppInfo_nexus_tag               13
#define rustplus_AppInfo_nexusId_tag             14
#define rustplus_AppInfo_nexusZone_tag           15
#define rustplus_AppInfo_camerasEnabled_tag      16
#define rustplus_AppTime_dayLengthMinutes_tag    1
#define rustplus_AppTime_timeScale_tag           2
#define rustplus_AppTime_sunrise_tag             3
#define rustplus_AppTime_sunset_tag              4
#define rustplus_AppTime_time_tag                5
#define rustplus_AppMap_width_tag                1
#define rustplus_AppMap_height_tag               2
#define rustplus_AppMap_jpgImage_tag             3
#define rustplus_AppMap_oceanMargin_tag          4
#define rustplus_AppMap_monuments_tag            5
#define rustplus_AppMap_background_tag           6
#define rustplus_AppMap_Monument_token_tag       1
#define rustplus_AppMap_Monument_x_tag           2
#define rustplus_AppMap_Monument_y_tag           3
#define rustplus_AppEntityPayload_value_tag      1
#define rustplus_AppEntityPayload_items_tag      2
#define rustplus_AppEntityPayload_capacity_tag   3
#define rustplus_AppEntityPayload_hasProtection_tag 4
#define rustplus_AppEntityPayload_protectionExpiry_tag 5
#define rustplus_AppEntityInfo_type_tag          1
#define rustplus_AppEntityInfo_payload_tag       3
#define rustplus_AppEntityPayload_Item_itemId_tag 1
#define rustplus_AppEntityPayload_Item_quantity_tag 2
#define rustplus_AppEntityPayload_Item_itemIsBlueprint_tag 3
#define rustplus_AppTeamInfo_leaderSteamId_tag   1
#define rustplus_AppTeamInfo_members_tag         2
#define rustplus_AppTeamInfo_mapNotes_tag        3
#define rustplus_AppTeamInfo_leaderMapNotes_tag  4
#define rustplus_AppTeamInfo_Member_steamId_tag  1
#define rustplus_AppTeamInfo_Member_name_tag     2
#define rustplus_AppTeamInfo_Member_x_tag        3
#define rustplus_AppTeamInfo_Member_y_tag        4
#define rustplus_AppTeamInfo_Member_isOnline_tag 5
#define rustplus_AppTeamInfo_Member_spawnTime_tag 6
#define rustplus_AppTeamInfo_Member_isAlive_tag  7
#define rustplus_AppTeamInfo_Member_deathTime_tag 8
#define rustplus_AppTeamInfo_Note_type_tag       2
#define rustplus_AppTeamInfo_Note_x_tag          3
#define rustplus_AppTeamInfo_Note_y_tag          4
#define rustplus_AppTeamInfo_Note_icon_tag       5
#define rustplus_AppTeamInfo_Note_colourIndex_tag 6
#define rustplus_AppTeamInfo_Note_label_tag      7
#define rustplus_AppTeamMessage_steamId_tag      1
#define rustplus_AppTeamMessage_name_tag         2
#define rustplus_AppTeamMessage_message_tag      3
#define rustplus_AppTeamMessage_color_tag        4
#define rustplus_AppTeamMessage_time_tag         5
#define rustplus_AppTeamChat_messages_tag        1
#define rustplus_AppMarker_id_tag                1
#define rustplus_AppMarker_type_tag              2
#define rustplus_AppMarker_x_tag                 3
#define rustplus_AppMarker_y_tag                 4
#define rustplus_AppMarker_steamId_tag           5
#define rustplus_AppMarker_rotation_tag          6
#define rustplus_AppMarker_radius_tag            7
#define rustplus_AppMarker_color1_tag            8
#define rustplus_AppMarker_color2_tag            9
#define rustplus_AppMarker_alpha_tag             10
#define rustplus_AppMarker_name_tag              11
#define rustplus_AppMarker_outOfStock_tag        12
#define rustplus_AppMarker_sellOrders_tag        13
#define rustplus_AppMarker_SellOrder_itemId_tag  1
#define rustplus_AppMarker_SellOrder_quantity_tag 2
#define rustplus_AppMarker_SellOrder_currencyId_tag 3
#define rustplus_AppMarker_SellOrder_costPerItem_tag 4
#define rustplus_AppMarker_SellOrder_amountInStock_tag 5
#define rustplus_AppMarker_SellOrder_itemIsBlueprint_tag 6
#define rustplus_AppMarker_SellOrder_currencyIsBlueprint_tag 7
#define rustplus_AppMarker_SellOrder_itemCondition_tag 8
#define rustplus_AppMarker_SellOrder_itemConditionMax_tag 9
#define rustplus_AppMarker_SellOrder_priceMultiplier_tag 10
#define rustplus_AppMapMarkers_markers_tag       1
#define rustplus_AppClanInfo_clanInfo_tag        1
#define rustplus_AppClanMessage_steamId_tag      1
#define rustplus_AppClanMessage_name_tag         2
#define rustplus_AppClanMessage_message_tag      3
#define rustplus_AppClanMessage_time_tag         4
#define rustplus_AppClanChat_messages_tag        1
#define rustplus_AppNexusAuth_serverId_tag       1
#define rustplus_AppNexusAuth_playerToken_tag    2
#define rustplus_AppTeamChanged_playerId_tag     1
#define rustplus_AppTeamChanged_teamInfo_tag     2
#define rustplus_AppNewTeamMessage_message_tag   1
#define rustplus_AppEntityChanged_entityId_tag   1
#define rustplus_AppEntityChanged_payload_tag    2
#define rustplus_AppClanChanged_clanInfo_tag     1
#define rustplus_AppNewClanMessage_clanId_tag    1
#define rustplus_AppNewClanMessage_message_tag   2
#define rustplus_AppCameraSubscribe_cameraId_tag 1
#define rustplus_AppCameraInput_buttons_tag      1
#define rustplus_AppCameraInput_mouseDelta_tag   2
#define rustplus_AppRequest_seq_tag              1
#define rustplus_AppRequest_playerId_tag         2
#define rustplus_AppRequest_playerToken_tag      3
#define rustplus_AppRequest_entityId_tag         4
#define rustplus_AppRequest_getInfo_tag          8
#define rustplus_AppRequest_getTime_tag          9
#define rustplus_AppRequest_getMap_tag           10
#define rustplus_AppRequest_getTeamInfo_tag      11
#define rustplus_AppRequest_getTeamChat_tag      12
#define rustplus_AppRequest_sendTeamMessage_tag  13
#define rustplus_AppRequest_getEntityInfo_tag    14
#define rustplus_AppRequest_setEntityValue_tag   15
#define rustplus_AppRequest_checkSubscription_tag 16
#define rustplus_AppRequest_setSubscription_tag  17
#define rustplus_AppRequest_getMapMarkers_tag    18
#define rustplus_AppRequest_promoteToLeader_tag  20
#define rustplus_AppRequest_getClanInfo_tag      21
#define rustplus_AppRequest_setClanMotd_tag      22
#define rustplus_AppRequest_getClanChat_tag      23
#define rustplus_AppRequest_sendClanMessage_tag  24
#define rustplus_AppRequest_getNexusAuth_tag     25
#define rustplus_AppRequest_cameraSubscribe_tag  30
#define rustplus_AppRequest_cameraUnsubscribe_tag 31
#define rustplus_AppRequest_cameraInput_tag      32
#define rustplus_AppCameraInfo_width_tag         1
#define rustplus_AppCameraInfo_height_tag        2
#define rustplus_AppCameraInfo_nearPlane_tag     3
#define rustplus_AppCameraInfo_farPlane_tag      4
#define rustplus_AppCameraInfo_controlFlags_tag  5
#define rustplus_AppResponse_seq_tag             1
#define rustplus_AppResponse_success_tag         4
#define rustplus_AppResponse_error_tag           5
#define rustplus_AppResponse_info_tag            6
#define rustplus_AppResponse_time_tag            7
#define rustplus_AppResponse_map_tag             8
#define rustplus_AppResponse_teamInfo_tag        9
#define rustplus_AppResponse_teamChat_tag        10
#define rustplus_AppResponse_entityInfo_tag      11
#define rustplus_AppResponse_flag_tag            12
#define rustplus_AppResponse_mapMarkers_tag      13
#define rustplus_AppResponse_clanInfo_tag        15
#define rustplus_AppResponse_clanChat_tag        16
#define rustplus_AppResponse_nexusAuth_tag       17
#define rustplus_AppResponse_cameraSubscribeInfo_tag 20
#define rustplus_AppCameraRays_verticalFov_tag   1
#define rustplus_AppCameraRays_sampleOffset_tag  2
#define rustplus_AppCameraRays_rayData_tag       3
#define rustplus_AppCameraRays_distance_tag      4
#define rustplus_AppCameraRays_entities_tag      5
#define rustplus_AppCameraRays_timeOfDay_tag     6
#define rustplus_AppBroadcast_teamChanged_tag    4
#define rustplus_AppBroadcast_teamMessage_tag    5
#define rustplus_AppBroadcast_entityChanged_tag  6
#define rustplus_AppBroadcast_clanChanged_tag    7
#define rustplus_AppBroadcast_clanMessage_tag    8
#define rustplus_AppBroadcast_cameraRays_tag     10
#define rustplus_AppMessage_response_tag         1
#define rustplus_AppMessage_broadcast_tag        2
#define rustplus_AppCameraRays_Entity_entityId_tag 1
#define rustplus_AppCameraRays_Entity_type_tag   2
#define rustplus_AppCameraRays_Entity_position_tag 3
#define rustplus_AppCameraRays_Entity_rotation_tag 4
#define rustplus_AppCameraRays_Entity_size_tag   5
#define rustplus_AppCameraRays_Entity_name_tag   6

/* Struct field encoding specification for nanopb */
#define rustplus_Vector2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2)
#define rustplus_Vector2_CALLBACK NULL
#define rustplus_Vector2_DEFAULT NULL

#define rustplus_Vector3_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define rustplus_Vector3_CALLBACK NULL
#define rustplus_Vector3_DEFAULT NULL

#define rustplus_Vector4_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    w,                 4)
#define rustplus_Vector4_CALLBACK NULL
#define rustplus_Vector4_DEFAULT NULL

#define rustplus_Half3_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define rustplus_Half3_CALLBACK NULL
#define rustplus_Half3_DEFAULT NULL

#define rustplus_Color_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, FLOAT,    r,                 1) \
X(a_, STATIC,   SINGULAR, FLOAT,    g,                 2) \
X(a_, STATIC,   SINGULAR, FLOAT,    b,                 3) \
X(a_, STATIC,   SINGULAR, FLOAT,    a,                 4)
#define rustplus_Color_CALLBACK NULL
#define rustplus_Color_DEFAULT NULL

#define rustplus_Ray_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  origin,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  direction,         2)
#define rustplus_Ray_CALLBACK NULL
#define rustplus_Ray_DEFAULT NULL
#define rustplus_Ray_origin_MSGTYPE rustplus_Vector3
#define rustplus_Ray_direction_MSGTYPE rustplus_Vector3

#define rustplus_ClanActionResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    requestId,         1) \
X(a, STATIC,   SINGULAR, INT32,    result,            2) \
X(a, STATIC,   SINGULAR, BOOL,     hasClanInfo,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanInfo,          4)
#define rustplus_ClanActionResult_CALLBACK NULL
#define rustplus_ClanActionResult_DEFAULT NULL
#define rustplus_ClanActionResult_clanInfo_MSGTYPE rustplus_ClanInfo

#define rustplus_ClanInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    clanId,            1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, INT64,    created,           3) \
X(a, STATIC,   SINGULAR, UINT64,   creator,           4) \
X(a, CALLBACK, OPTIONAL, STRING,   motd,              5) \
X(a, STATIC,   SINGULAR, INT64,    motdTimestamp,     6) \
X(a, STATIC,   SINGULAR, UINT64,   motdAuthor,        7) \
X(a, CALLBACK, OPTIONAL, BYTES,    logo,              8) \
X(a, STATIC,   SINGULAR, SINT32,   color,             9) \
X(a, CALLBACK, REPEATED, MESSAGE,  roles,            10) \
X(a, CALLBACK, REPEATED, MESSAGE,  members,          11) \
X(a, CALLBACK, REPEATED, MESSAGE,  invites,          12) \
X(a, STATIC,   OPTIONAL, INT32,    maxMemberCount,   13) \
X(a, STATIC,   SINGULAR, INT64,    score,            14)
#define rustplus_ClanInfo_CALLBACK pb_default_field_callback
#define rustplus_ClanInfo_DEFAULT NULL
#define rustplus_ClanInfo_roles_MSGTYPE rustplus_ClanInfo_Role
#define rustplus_ClanInfo_members_MSGTYPE rustplus_ClanInfo_Member
#define rustplus_ClanInfo_invites_MSGTYPE rustplus_ClanInfo_Invite

#define rustplus_ClanInfo_Role_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    roleId,            1) \
X(a, STATIC,   SINGULAR, INT32,    rank,              2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, BOOL,     canSetMotd,        4) \
X(a, STATIC,   SINGULAR, BOOL,     canSetLogo,        5) \
X(a, STATIC,   SINGULAR, BOOL,     canInvite,         6) \
X(a, STATIC,   SINGULAR, BOOL,     canKick,           7) \
X(a, STATIC,   SINGULAR, BOOL,     canPromote,        8) \
X(a, STATIC,   SINGULAR, BOOL,     canDemote,         9) \
X(a, STATIC,   SINGULAR, BOOL,     canSetPlayerNotes,  10) \
X(a, STATIC,   SINGULAR, BOOL,     canAccessLogs,    11) \
X(a, STATIC,   SINGULAR, BOOL,     canAccessScoreEvents,  12)
#define rustplus_ClanInfo_Role_CALLBACK pb_default_field_callback
#define rustplus_ClanInfo_Role_DEFAULT NULL

#define rustplus_ClanInfo_Member_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1) \
X(a, STATIC,   SINGULAR, INT32,    roleId,            2) \
X(a, STATIC,   SINGULAR, INT64,    joined,            3) \
X(a, STATIC,   SINGULAR, INT64,    lastSeen,          4) \
X(a, CALLBACK, OPTIONAL, STRING,   notes,             5) \
X(a, STATIC,   SINGULAR, BOOL,     online,            6)
#define rustplus_ClanInfo_Member_CALLBACK pb_default_field_callback
#define rustplus_ClanInfo_Member_DEFAULT NULL

#define rustplus_ClanInfo_Invite_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1) \
X(a, STATIC,   SINGULAR, UINT64,   recruiter,         2) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         3)
#define rustplus_ClanInfo_Invite_CALLBACK NULL
#define rustplus_ClanInfo_Invite_DEFAULT NULL

#define rustplus_ClanLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    clanId,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  logEntries,        2)
#define rustplus_ClanLog_CALLBACK pb_default_field_callback
#define rustplus_ClanLog_DEFAULT NULL
#define rustplus_ClanLog_logEntries_MSGTYPE rustplus_ClanLog_Entry

#define rustplus_ClanLog_Entry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         1) \
X(a, CALLBACK, SINGULAR, STRING,   eventKey,          2) \
X(a, CALLBACK, OPTIONAL, STRING,   arg1,              3) \
X(a, CALLBACK, OPTIONAL, STRING,   arg2,              4) \
X(a, CALLBACK, OPTIONAL, STRING,   arg3,              5) \
X(a, CALLBACK, OPTIONAL, STRING,   arg4,              6)
#define rustplus_ClanLog_Entry_CALLBACK pb_default_field_callback
#define rustplus_ClanLog_Entry_DEFAULT NULL

#define rustplus_ClanInvitations_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  invitations,       1)
#define rustplus_ClanInvitations_CALLBACK pb_default_field_callback
#define rustplus_ClanInvitations_DEFAULT NULL
#define rustplus_ClanInvitations_invitations_MSGTYPE rustplus_ClanInvitations_Invitation

#define rustplus_ClanInvitations_Invitation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    clanId,            1) \
X(a, STATIC,   SINGULAR, UINT64,   recruiter,         2) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         3)
#define rustplus_ClanInvitations_Invitation_CALLBACK NULL
#define rustplus_ClanInvitations_Invitation_DEFAULT NULL

#define rustplus_AppRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, UINT64,   playerId,          2) \
X(a, STATIC,   SINGULAR, INT32,    playerToken,       3) \
X(a, STATIC,   OPTIONAL, UINT32,   entityId,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getInfo,           8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getTime,           9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getMap,           10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getTeamInfo,      11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getTeamChat,      12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sendTeamMessage,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getEntityInfo,    14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  setEntityValue,   15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  checkSubscription,  16) \
X(a, STATIC,   OPTIONAL, MESSAGE,  setSubscription,  17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getMapMarkers,    18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  promoteToLeader,  20) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getClanInfo,      21) \
X(a, STATIC,   OPTIONAL, MESSAGE,  setClanMotd,      22) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getClanChat,      23) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sendClanMessage,  24) \
X(a, STATIC,   OPTIONAL, MESSAGE,  getNexusAuth,     25) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cameraSubscribe,  30) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cameraUnsubscribe,  31) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cameraInput,      32)
#define rustplus_AppRequest_CALLBACK NULL
#define rustplus_AppRequest_DEFAULT NULL
#define rustplus_AppRequest_getInfo_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_getTime_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_getMap_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_getTeamInfo_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_getTeamChat_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_sendTeamMessage_MSGTYPE rustplus_AppSendMessage
#define rustplus_AppRequest_getEntityInfo_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_setEntityValue_MSGTYPE rustplus_AppSetEntityValue
#define rustplus_AppRequest_checkSubscription_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_setSubscription_MSGTYPE rustplus_AppFlag
#define rustplus_AppRequest_getMapMarkers_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_promoteToLeader_MSGTYPE rustplus_AppPromoteToLeader
#define rustplus_AppRequest_getClanInfo_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_setClanMotd_MSGTYPE rustplus_AppSendMessage
#define rustplus_AppRequest_getClanChat_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_sendClanMessage_MSGTYPE rustplus_AppSendMessage
#define rustplus_AppRequest_getNexusAuth_MSGTYPE rustplus_AppGetNexusAuth
#define rustplus_AppRequest_cameraSubscribe_MSGTYPE rustplus_AppCameraSubscribe
#define rustplus_AppRequest_cameraUnsubscribe_MSGTYPE rustplus_AppEmpty
#define rustplus_AppRequest_cameraInput_MSGTYPE rustplus_AppCameraInput

#define rustplus_AppMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  broadcast,         2)
#define rustplus_AppMessage_CALLBACK NULL
#define rustplus_AppMessage_DEFAULT NULL
#define rustplus_AppMessage_response_MSGTYPE rustplus_AppResponse
#define rustplus_AppMessage_broadcast_MSGTYPE rustplus_AppBroadcast

#define rustplus_AppResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  success,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error,             5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  map,               8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teamInfo,          9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teamChat,         10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  entityInfo,       11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  flag,             12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mapMarkers,       13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanInfo,         15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanChat,         16) \
X(a, STATIC,   OPTIONAL, MESSAGE,  nexusAuth,        17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cameraSubscribeInfo,  20)
#define rustplus_AppResponse_CALLBACK NULL
#define rustplus_AppResponse_DEFAULT NULL
#define rustplus_AppResponse_success_MSGTYPE rustplus_AppSuccess
#define rustplus_AppResponse_error_MSGTYPE rustplus_AppError
#define rustplus_AppResponse_info_MSGTYPE rustplus_AppInfo
#define rustplus_AppResponse_time_MSGTYPE rustplus_AppTime
#define rustplus_AppResponse_map_MSGTYPE rustplus_AppMap
#define rustplus_AppResponse_teamInfo_MSGTYPE rustplus_AppTeamInfo
#define rustplus_AppResponse_teamChat_MSGTYPE rustplus_AppTeamChat
#define rustplus_AppResponse_entityInfo_MSGTYPE rustplus_AppEntityInfo
#define rustplus_AppResponse_flag_MSGTYPE rustplus_AppFlag
#define rustplus_AppResponse_mapMarkers_MSGTYPE rustplus_AppMapMarkers
#define rustplus_AppResponse_clanInfo_MSGTYPE rustplus_AppClanInfo
#define rustplus_AppResponse_clanChat_MSGTYPE rustplus_AppClanChat
#define rustplus_AppResponse_nexusAuth_MSGTYPE rustplus_AppNexusAuth
#define rustplus_AppResponse_cameraSubscribeInfo_MSGTYPE rustplus_AppCameraInfo

#define rustplus_AppBroadcast_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teamChanged,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teamMessage,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  entityChanged,     6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanChanged,       7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanMessage,       8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cameraRays,       10)
#define rustplus_AppBroadcast_CALLBACK NULL
#define rustplus_AppBroadcast_DEFAULT NULL
#define rustplus_AppBroadcast_teamChanged_MSGTYPE rustplus_AppTeamChanged
#define rustplus_AppBroadcast_teamMessage_MSGTYPE rustplus_AppNewTeamMessage
#define rustplus_AppBroadcast_entityChanged_MSGTYPE rustplus_AppEntityChanged
#define rustplus_AppBroadcast_clanChanged_MSGTYPE rustplus_AppClanChanged
#define rustplus_AppBroadcast_clanMessage_MSGTYPE rustplus_AppNewClanMessage
#define rustplus_AppBroadcast_cameraRays_MSGTYPE rustplus_AppCameraRays

#define rustplus_AppEmpty_FIELDLIST(X, a) \

#define rustplus_AppEmpty_CALLBACK NULL
#define rustplus_AppEmpty_DEFAULT NULL

#define rustplus_AppSendMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define rustplus_AppSendMessage_CALLBACK pb_default_field_callback
#define rustplus_AppSendMessage_DEFAULT NULL

#define rustplus_AppSetEntityValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1)
#define rustplus_AppSetEntityValue_CALLBACK NULL
#define rustplus_AppSetEntityValue_DEFAULT NULL

#define rustplus_AppPromoteToLeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1)
#define rustplus_AppPromoteToLeader_CALLBACK NULL
#define rustplus_AppPromoteToLeader_DEFAULT NULL

#define rustplus_AppGetNexusAuth_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   appKey,            1)
#define rustplus_AppGetNexusAuth_CALLBACK pb_default_field_callback
#define rustplus_AppGetNexusAuth_DEFAULT NULL

#define rustplus_AppSuccess_FIELDLIST(X, a) \

#define rustplus_AppSuccess_CALLBACK NULL
#define rustplus_AppSuccess_DEFAULT NULL

#define rustplus_AppError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   error,             1)
#define rustplus_AppError_CALLBACK pb_default_field_callback
#define rustplus_AppError_DEFAULT NULL

#define rustplus_AppFlag_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     value,             1)
#define rustplus_AppFlag_CALLBACK NULL
#define rustplus_AppFlag_DEFAULT NULL

#define rustplus_AppInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   headerImage,       2) \
X(a, CALLBACK, SINGULAR, STRING,   url,               3) \
X(a, CALLBACK, SINGULAR, STRING,   map,               4) \
X(a, STATIC,   SINGULAR, UINT32,   mapSize,           5) \
X(a, STATIC,   SINGULAR, UINT32,   wipeTime,          6) \
X(a, STATIC,   SINGULAR, UINT32,   players,           7) \
X(a, STATIC,   SINGULAR, UINT32,   maxPlayers,        8) \
X(a, STATIC,   SINGULAR, UINT32,   queuedPlayers,     9) \
X(a, STATIC,   SINGULAR, UINT32,   seed,             10) \
X(a, STATIC,   SINGULAR, UINT32,   salt,             11) \
X(a, CALLBACK, OPTIONAL, STRING,   logoImage,        12) \
X(a, CALLBACK, OPTIONAL, STRING,   nexus,            13) \
X(a, STATIC,   SINGULAR, INT32,    nexusId,          14) \
X(a, CALLBACK, OPTIONAL, STRING,   nexusZone,        15) \
X(a, STATIC,   SINGULAR, BOOL,     camerasEnabled,   16)
#define rustplus_AppInfo_CALLBACK pb_default_field_callback
#define rustplus_AppInfo_DEFAULT NULL

#define rustplus_AppTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    dayLengthMinutes,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    timeScale,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    sunrise,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    sunset,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    time,              5)
#define rustplus_AppTime_CALLBACK NULL
#define rustplus_AppTime_DEFAULT NULL

#define rustplus_AppMap_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    jpgImage,          3) \
X(a, STATIC,   SINGULAR, INT32,    oceanMargin,       4) \
X(a, CALLBACK, REPEATED, MESSAGE,  monuments,         5) \
X(a, CALLBACK, OPTIONAL, STRING,   background,        6)
#define rustplus_AppMap_CALLBACK pb_default_field_callback
#define rustplus_AppMap_DEFAULT NULL
#define rustplus_AppMap_monuments_MSGTYPE rustplus_AppMap_Monument

#define rustplus_AppMap_Monument_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   token,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 3)
#define rustplus_AppMap_Monument_CALLBACK pb_default_field_callback
#define rustplus_AppMap_Monument_DEFAULT NULL

#define rustplus_AppEntityInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payload,           3)
#define rustplus_AppEntityInfo_CALLBACK NULL
#define rustplus_AppEntityInfo_DEFAULT NULL
#define rustplus_AppEntityInfo_payload_MSGTYPE rustplus_AppEntityPayload

#define rustplus_AppEntityPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     value,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             2) \
X(a, STATIC,   SINGULAR, INT32,    capacity,          3) \
X(a, STATIC,   OPTIONAL, BOOL,     hasProtection,     4) \
X(a, STATIC,   SINGULAR, UINT32,   protectionExpiry,   5)
#define rustplus_AppEntityPayload_CALLBACK pb_default_field_callback
#define rustplus_AppEntityPayload_DEFAULT NULL
#define rustplus_AppEntityPayload_items_MSGTYPE rustplus_AppEntityPayload_Item

#define rustplus_AppEntityPayload_Item_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    itemId,            1) \
X(a, STATIC,   SINGULAR, INT32,    quantity,          2) \
X(a, STATIC,   SINGULAR, BOOL,     itemIsBlueprint,   3)
#define rustplus_AppEntityPayload_Item_CALLBACK NULL
#define rustplus_AppEntityPayload_Item_DEFAULT NULL

#define rustplus_AppTeamInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   leaderSteamId,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  members,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  mapNotes,          3) \
X(a, CALLBACK, REPEATED, MESSAGE,  leaderMapNotes,    4)
#define rustplus_AppTeamInfo_CALLBACK pb_default_field_callback
#define rustplus_AppTeamInfo_DEFAULT NULL
#define rustplus_AppTeamInfo_members_MSGTYPE rustplus_AppTeamInfo_Member
#define rustplus_AppTeamInfo_mapNotes_MSGTYPE rustplus_AppTeamInfo_Note
#define rustplus_AppTeamInfo_leaderMapNotes_MSGTYPE rustplus_AppTeamInfo_Note

#define rustplus_AppTeamInfo_Member_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, BOOL,     isOnline,          5) \
X(a, STATIC,   SINGULAR, UINT32,   spawnTime,         6) \
X(a, STATIC,   SINGULAR, BOOL,     isAlive,           7) \
X(a, STATIC,   SINGULAR, UINT32,   deathTime,         8)
#define rustplus_AppTeamInfo_Member_CALLBACK pb_default_field_callback
#define rustplus_AppTeamInfo_Member_DEFAULT NULL

#define rustplus_AppTeamInfo_Note_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, UENUM,    icon,              5) \
X(a, STATIC,   SINGULAR, UENUM,    colourIndex,       6) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             7)
#define rustplus_AppTeamInfo_Note_CALLBACK pb_default_field_callback
#define rustplus_AppTeamInfo_Note_DEFAULT NULL

#define rustplus_AppTeamMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   message,           3) \
X(a, CALLBACK, SINGULAR, STRING,   color,             4) \
X(a, STATIC,   SINGULAR, UINT32,   time,              5)
#define rustplus_AppTeamMessage_CALLBACK pb_default_field_callback
#define rustplus_AppTeamMessage_DEFAULT NULL

#define rustplus_AppTeamChat_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  messages,          1)
#define rustplus_AppTeamChat_CALLBACK pb_default_field_callback
#define rustplus_AppTeamChat_DEFAULT NULL
#define rustplus_AppTeamChat_messages_MSGTYPE rustplus_AppTeamMessage

#define rustplus_AppMarker_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    rotation,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    radius,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color1,            8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color2,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    alpha,            10) \
X(a, CALLBACK, OPTIONAL, STRING,   name,             11) \
X(a, STATIC,   SINGULAR, BOOL,     outOfStock,       12) \
X(a, CALLBACK, REPEATED, MESSAGE,  sellOrders,       13)
#define rustplus_AppMarker_CALLBACK pb_default_field_callback
#define rustplus_AppMarker_DEFAULT NULL
#define rustplus_AppMarker_color1_MSGTYPE rustplus_Vector4
#define rustplus_AppMarker_color2_MSGTYPE rustplus_Vector4
#define rustplus_AppMarker_sellOrders_MSGTYPE rustplus_AppMarker_SellOrder

#define rustplus_AppMarker_SellOrder_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    itemId,            1) \
X(a, STATIC,   SINGULAR, INT32,    quantity,          2) \
X(a, STATIC,   SINGULAR, INT32,    currencyId,        3) \
X(a, STATIC,   SINGULAR, INT32,    costPerItem,       4) \
X(a, STATIC,   SINGULAR, INT32,    amountInStock,     5) \
X(a, STATIC,   SINGULAR, BOOL,     itemIsBlueprint,   6) \
X(a, STATIC,   SINGULAR, BOOL,     currencyIsBlueprint,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    itemCondition,     8) \
X(a, STATIC,   SINGULAR, FLOAT,    itemConditionMax,   9) \
X(a, STATIC,   SINGULAR, FLOAT,    priceMultiplier,  10)
#define rustplus_AppMarker_SellOrder_CALLBACK NULL
#define rustplus_AppMarker_SellOrder_DEFAULT NULL

#define rustplus_AppMapMarkers_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  markers,           1)
#define rustplus_AppMapMarkers_CALLBACK pb_default_field_callback
#define rustplus_AppMapMarkers_DEFAULT NULL
#define rustplus_AppMapMarkers_markers_MSGTYPE rustplus_AppMarker

#define rustplus_AppClanInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanInfo,          1)
#define rustplus_AppClanInfo_CALLBACK NULL
#define rustplus_AppClanInfo_DEFAULT NULL
#define rustplus_AppClanInfo_clanInfo_MSGTYPE rustplus_ClanInfo

#define rustplus_AppClanMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   steamId,           1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, INT64,    time,              4)
#define rustplus_AppClanMessage_CALLBACK pb_default_field_callback
#define rustplus_AppClanMessage_DEFAULT NULL

#define rustplus_AppClanChat_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  messages,          1)
#define rustplus_AppClanChat_CALLBACK pb_default_field_callback
#define rustplus_AppClanChat_DEFAULT NULL
#define rustplus_AppClanChat_messages_MSGTYPE rustplus_AppClanMessage

#define rustplus_AppNexusAuth_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   serverId,          1) \
X(a, STATIC,   SINGULAR, INT32,    playerToken,       2)
#define rustplus_AppNexusAuth_CALLBACK pb_default_field_callback
#define rustplus_AppNexusAuth_DEFAULT NULL

#define rustplus_AppTeamChanged_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   playerId,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teamInfo,          2)
#define rustplus_AppTeamChanged_CALLBACK NULL
#define rustplus_AppTeamChanged_DEFAULT NULL
#define rustplus_AppTeamChanged_teamInfo_MSGTYPE rustplus_AppTeamInfo

#define rustplus_AppNewTeamMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define rustplus_AppNewTeamMessage_CALLBACK NULL
#define rustplus_AppNewTeamMessage_DEFAULT NULL
#define rustplus_AppNewTeamMessage_message_MSGTYPE rustplus_AppTeamMessage

#define rustplus_AppEntityChanged_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   entityId,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payload,           2)
#define rustplus_AppEntityChanged_CALLBACK NULL
#define rustplus_AppEntityChanged_DEFAULT NULL
#define rustplus_AppEntityChanged_payload_MSGTYPE rustplus_AppEntityPayload

#define rustplus_AppClanChanged_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  clanInfo,          1)
#define rustplus_AppClanChanged_CALLBACK NULL
#define rustplus_AppClanChanged_DEFAULT NULL
#define rustplus_AppClanChanged_clanInfo_MSGTYPE rustplus_ClanInfo

#define rustplus_AppNewClanMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    clanId,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           2)
#define rustplus_AppNewClanMessage_CALLBACK NULL
#define rustplus_AppNewClanMessage_DEFAULT NULL
#define rustplus_AppNewClanMessage_message_MSGTYPE rustplus_AppClanMessage

#define rustplus_AppCameraSubscribe_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   cameraId,          1)
#define rustplus_AppCameraSubscribe_CALLBACK pb_default_field_callback
#define rustplus_AppCameraSubscribe_DEFAULT NULL

#define rustplus_AppCameraInput_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    buttons,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mouseDelta,        2)
#define rustplus_AppCameraInput_CALLBACK NULL
#define rustplus_AppCameraInput_DEFAULT NULL
#define rustplus_AppCameraInput_mouseDelta_MSGTYPE rustplus_Vector2

#define rustplus_AppCameraInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    width,             1) \
X(a, STATIC,   SINGULAR, INT32,    height,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    nearPlane,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    farPlane,          4) \
X(a, STATIC,   SINGULAR, INT32,    controlFlags,      5)
#define rustplus_AppCameraInfo_CALLBACK NULL
#define rustplus_AppCameraInfo_DEFAULT NULL

#define rustplus_AppCameraRays_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    verticalFov,       1) \
X(a, STATIC,   SINGULAR, INT32,    sampleOffset,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    rayData,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    distance,          4) \
X(a, CALLBACK, REPEATED, MESSAGE,  entities,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    timeOfDay,         6)
#define rustplus_AppCameraRays_CALLBACK pb_default_field_callback
#define rustplus_AppCameraRays_DEFAULT NULL
#define rustplus_AppCameraRays_entities_MSGTYPE rustplus_AppCameraRays_Entity

#define rustplus_AppCameraRays_Entity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   entityId,          1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rotation,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  size,              5) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              6)
#define rustplus_AppCameraRays_Entity_CALLBACK pb_default_field_callback
#define rustplus_AppCameraRays_Entity_DEFAULT NULL
#define rustplus_AppCameraRays_Entity_position_MSGTYPE rustplus_Vector3
#define rustplus_AppCameraRays_Entity_rotation_MSGTYPE rustplus_Vector3
#define rustplus_AppCameraRays_Entity_size_MSGTYPE rustplus_Vector3

extern const pb_msgdesc_t rustplus_Vector2_msg;
extern const pb_msgdesc_t rustplus_Vector3_msg;
extern const pb_msgdesc_t rustplus_Vector4_msg;
extern const pb_msgdesc_t rustplus_Half3_msg;
extern const pb_msgdesc_t rustplus_Color_msg;
extern const pb_msgdesc_t rustplus_Ray_msg;
extern const pb_msgdesc_t rustplus_ClanActionResult_msg;
extern const pb_msgdesc_t rustplus_ClanInfo_msg;
extern const pb_msgdesc_t rustplus_ClanInfo_Role_msg;
extern const pb_msgdesc_t rustplus_ClanInfo_Member_msg;
extern const pb_msgdesc_t rustplus_ClanInfo_Invite_msg;
extern const pb_msgdesc_t rustplus_ClanLog_msg;
extern const pb_msgdesc_t rustplus_ClanLog_Entry_msg;
extern const pb_msgdesc_t rustplus_ClanInvitations_msg;
extern const pb_msgdesc_t rustplus_ClanInvitations_Invitation_msg;
extern const pb_msgdesc_t rustplus_AppRequest_msg;
extern const pb_msgdesc_t rustplus_AppMessage_msg;
extern const pb_msgdesc_t rustplus_AppResponse_msg;
extern const pb_msgdesc_t rustplus_AppBroadcast_msg;
extern const pb_msgdesc_t rustplus_AppEmpty_msg;
extern const pb_msgdesc_t rustplus_AppSendMessage_msg;
extern const pb_msgdesc_t rustplus_AppSetEntityValue_msg;
extern const pb_msgdesc_t rustplus_AppPromoteToLeader_msg;
extern const pb_msgdesc_t rustplus_AppGetNexusAuth_msg;
extern const pb_msgdesc_t rustplus_AppSuccess_msg;
extern const pb_msgdesc_t rustplus_AppError_msg;
extern const pb_msgdesc_t rustplus_AppFlag_msg;
extern const pb_msgdesc_t rustplus_AppInfo_msg;
extern const pb_msgdesc_t rustplus_AppTime_msg;
extern const pb_msgdesc_t rustplus_AppMap_msg;
extern const pb_msgdesc_t rustplus_AppMap_Monument_msg;
extern const pb_msgdesc_t rustplus_AppEntityInfo_msg;
extern const pb_msgdesc_t rustplus_AppEntityPayload_msg;
extern const pb_msgdesc_t rustplus_AppEntityPayload_Item_msg;
extern const pb_msgdesc_t rustplus_AppTeamInfo_msg;
extern const pb_msgdesc_t rustplus_AppTeamInfo_Member_msg;
extern const pb_msgdesc_t rustplus_AppTeamInfo_Note_msg;
extern const pb_msgdesc_t rustplus_AppTeamMessage_msg;
extern const pb_msgdesc_t rustplus_AppTeamChat_msg;
extern const pb_msgdesc_t rustplus_AppMarker_msg;
extern const pb_msgdesc_t rustplus_AppMarker_SellOrder_msg;
extern const pb_msgdesc_t rustplus_AppMapMarkers_msg;
extern const pb_msgdesc_t rustplus_AppClanInfo_msg;
extern const pb_msgdesc_t rustplus_AppClanMessage_msg;
extern const pb_msgdesc_t rustplus_AppClanChat_msg;
extern const pb_msgdesc_t rustplus_AppNexusAuth_msg;
extern const pb_msgdesc_t rustplus_AppTeamChanged_msg;
extern const pb_msgdesc_t rustplus_AppNewTeamMessage_msg;
extern const pb_msgdesc_t rustplus_AppEntityChanged_msg;
extern const pb_msgdesc_t rustplus_AppClanChanged_msg;
extern const pb_msgdesc_t rustplus_AppNewClanMessage_msg;
extern const pb_msgdesc_t rustplus_AppCameraSubscribe_msg;
extern const pb_msgdesc_t rustplus_AppCameraInput_msg;
extern const pb_msgdesc_t rustplus_AppCameraInfo_msg;
extern const pb_msgdesc_t rustplus_AppCameraRays_msg;
extern const pb_msgdesc_t rustplus_AppCameraRays_Entity_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rustplus_Vector2_fields &rustplus_Vector2_msg
#define rustplus_Vector3_fields &rustplus_Vector3_msg
#define rustplus_Vector4_fields &rustplus_Vector4_msg
#define rustplus_Half3_fields &rustplus_Half3_msg
#define rustplus_Color_fields &rustplus_Color_msg
#define rustplus_Ray_fields &rustplus_Ray_msg
#define rustplus_ClanActionResult_fields &rustplus_ClanActionResult_msg
#define rustplus_ClanInfo_fields &rustplus_ClanInfo_msg
#define rustplus_ClanInfo_Role_fields &rustplus_ClanInfo_Role_msg
#define rustplus_ClanInfo_Member_fields &rustplus_ClanInfo_Member_msg
#define rustplus_ClanInfo_Invite_fields &rustplus_ClanInfo_Invite_msg
#define rustplus_ClanLog_fields &rustplus_ClanLog_msg
#define rustplus_ClanLog_Entry_fields &rustplus_ClanLog_Entry_msg
#define rustplus_ClanInvitations_fields &rustplus_ClanInvitations_msg
#define rustplus_ClanInvitations_Invitation_fields &rustplus_ClanInvitations_Invitation_msg
#define rustplus_AppRequest_fields &rustplus_AppRequest_msg
#define rustplus_AppMessage_fields &rustplus_AppMessage_msg
#define rustplus_AppResponse_fields &rustplus_AppResponse_msg
#define rustplus_AppBroadcast_fields &rustplus_AppBroadcast_msg
#define rustplus_AppEmpty_fields &rustplus_AppEmpty_msg
#define rustplus_AppSendMessage_fields &rustplus_AppSendMessage_msg
#define rustplus_AppSetEntityValue_fields &rustplus_AppSetEntityValue_msg
#define rustplus_AppPromoteToLeader_fields &rustplus_AppPromoteToLeader_msg
#define rustplus_AppGetNexusAuth_fields &rustplus_AppGetNexusAuth_msg
#define rustplus_AppSuccess_fields &rustplus_AppSuccess_msg
#define rustplus_AppError_fields &rustplus_AppError_msg
#define rustplus_AppFlag_fields &rustplus_AppFlag_msg
#define rustplus_AppInfo_fields &rustplus_AppInfo_msg
#define rustplus_AppTime_fields &rustplus_AppTime_msg
#define rustplus_AppMap_fields &rustplus_AppMap_msg
#define rustplus_AppMap_Monument_fields &rustplus_AppMap_Monument_msg
#define rustplus_AppEntityInfo_fields &rustplus_AppEntityInfo_msg
#define rustplus_AppEntityPayload_fields &rustplus_AppEntityPayload_msg
#define rustplus_AppEntityPayload_Item_fields &rustplus_AppEntityPayload_Item_msg
#define rustplus_AppTeamInfo_fields &rustplus_AppTeamInfo_msg
#define rustplus_AppTeamInfo_Member_fields &rustplus_AppTeamInfo_Member_msg
#define rustplus_AppTeamInfo_Note_fields &rustplus_AppTeamInfo_Note_msg
#define rustplus_AppTeamMessage_fields &rustplus_AppTeamMessage_msg
#define rustplus_AppTeamChat_fields &rustplus_AppTeamChat_msg
#define rustplus_AppMarker_fields &rustplus_AppMarker_msg
#define rustplus_AppMarker_SellOrder_fields &rustplus_AppMarker_SellOrder_msg
#define rustplus_AppMapMarkers_fields &rustplus_AppMapMarkers_msg
#define rustplus_AppClanInfo_fields &rustplus_AppClanInfo_msg
#define rustplus_AppClanMessage_fields &rustplus_AppClanMessage_msg
#define rustplus_AppClanChat_fields &rustplus_AppClanChat_msg
#define rustplus_AppNexusAuth_fields &rustplus_AppNexusAuth_msg
#define rustplus_AppTeamChanged_fields &rustplus_AppTeamChanged_msg
#define rustplus_AppNewTeamMessage_fields &rustplus_AppNewTeamMessage_msg
#define rustplus_AppEntityChanged_fields &rustplus_AppEntityChanged_msg
#define rustplus_AppClanChanged_fields &rustplus_AppClanChanged_msg
#define rustplus_AppNewClanMessage_fields &rustplus_AppNewClanMessage_msg
#define rustplus_AppCameraSubscribe_fields &rustplus_AppCameraSubscribe_msg
#define rustplus_AppCameraInput_fields &rustplus_AppCameraInput_msg
#define rustplus_AppCameraInfo_fields &rustplus_AppCameraInfo_msg
#define rustplus_AppCameraRays_fields &rustplus_AppCameraRays_msg
#define rustplus_AppCameraRays_Entity_fields &rustplus_AppCameraRays_Entity_msg

/* Maximum encoded size of messages (where known) */
/* rustplus_ClanActionResult_size depends on runtime parameters */
/* rustplus_ClanInfo_size depends on runtime parameters */
/* rustplus_ClanInfo_Role_size depends on runtime parameters */
/* rustplus_ClanInfo_Member_size depends on runtime parameters */
/* rustplus_ClanLog_size depends on runtime parameters */
/* rustplus_ClanLog_Entry_size depends on runtime parameters */
/* rustplus_ClanInvitations_size depends on runtime parameters */
/* rustplus_AppRequest_size depends on runtime parameters */
/* rustplus_AppMessage_size depends on runtime parameters */
/* rustplus_AppResponse_size depends on runtime parameters */
/* rustplus_AppBroadcast_size depends on runtime parameters */
/* rustplus_AppSendMessage_size depends on runtime parameters */
/* rustplus_AppGetNexusAuth_size depends on runtime parameters */
/* rustplus_AppError_size depends on runtime parameters */
/* rustplus_AppInfo_size depends on runtime parameters */
/* rustplus_AppMap_size depends on runtime parameters */
/* rustplus_AppMap_Monument_size depends on runtime parameters */
/* rustplus_AppEntityInfo_size depends on runtime parameters */
/* rustplus_AppEntityPayload_size depends on runtime parameters */
/* rustplus_AppTeamInfo_size depends on runtime parameters */
/* rustplus_AppTeamInfo_Member_size depends on runtime parameters */
/* rustplus_AppTeamInfo_Note_size depends on runtime parameters */
/* rustplus_AppTeamMessage_size depends on runtime parameters */
/* rustplus_AppTeamChat_size depends on runtime parameters */
/* rustplus_AppMarker_size depends on runtime parameters */
/* rustplus_AppMapMarkers_size depends on runtime parameters */
/* rustplus_AppClanInfo_size depends on runtime parameters */
/* rustplus_AppClanMessage_size depends on runtime parameters */
/* rustplus_AppClanChat_size depends on runtime parameters */
/* rustplus_AppNexusAuth_size depends on runtime parameters */
/* rustplus_AppTeamChanged_size depends on runtime parameters */
/* rustplus_AppNewTeamMessage_size depends on runtime parameters */
/* rustplus_AppEntityChanged_size depends on runtime parameters */
/* rustplus_AppClanChanged_size depends on runtime parameters */
/* rustplus_AppNewClanMessage_size depends on runtime parameters */
/* rustplus_AppCameraSubscribe_size depends on runtime parameters */
/* rustplus_AppCameraRays_size depends on runtime parameters */
/* rustplus_AppCameraRays_Entity_size depends on runtime parameters */
#define RUSTPLUS_RUSTPLUS_PB_H_MAX_SIZE          rustplus_AppMarker_SellOrder_size
#define rustplus_AppCameraInfo_size              43
#define rustplus_AppCameraInput_size             23
#define rustplus_AppEmpty_size                   0
#define rustplus_AppEntityPayload_Item_size      24
#define rustplus_AppFlag_size                    2
#define rustplus_AppMarker_SellOrder_size        74
#define rustplus_AppPromoteToLeader_size         11
#define rustplus_AppSetEntityValue_size          2
#define rustplus_AppSuccess_size                 0
#define rustplus_AppTime_size                    25
#define rustplus_ClanInfo_Invite_size            33
#define rustplus_ClanInvitations_Invitation_size 33
#define rustplus_Color_size                      20
#define rustplus_Half3_size                      15
#define rustplus_Ray_size                        34
#define rustplus_Vector2_size                    10
#define rustplus_Vector3_size                    15
#define rustplus_Vector4_size                    20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
